# Generated by Django 6.0.3 on 2026-04-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(default='POST', max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('latency_ms', models.FloatField()),
                ('is_error', models.BooleanField(db_index=True, default=False)),
                ('exception', models.CharField(blank=True, default='', max_length=128)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('drift_score', models.FloatField(default=0.0)),
                ('drift_alert', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Inference Metric',
                'verbose_name_plural': 'Inference Metrics',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['recorded_at', 'is_error'], name='llm_monitor_recorde_101dac_idx'), models.Index(fields=['recorded_at', 'drift_alert'], name='llm_monitor_recorde_25627b_idx'), models.Index(fields=['path', 'recorded_at'], name='llm_monitor_path_c2afa0_idx')],
            },
        ),
    ]
