"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-oxl=tn#mrkbnl(&r$d8elga=o19$bhsm0ah!v1ki5z-b$q08k1'

DEBUG = True

ALLOWED_HOSTS = ['*']  # ✅ corrigé pour les tests


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'llm_monitor',  
    'dashboard',
    'alerting',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'llm_monitor.middleware.LLMMonitoringMiddleware',  # ✅ Student #3
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files

STATIC_URL = 'static/'


# =============================================================================
# ✅ Student #3 — Configuration du monitoring online
# =============================================================================

LLM_MONITOR_PATHS = ['/api/llm/', '/api/infer/', '/api/chat/']
LLM_MONITOR_API_KEY = 'monitor-secret-key-change-in-prod'
LLM_DRIFT_THRESHOLD = 0.35
LLM_DRIFT_REFERENCE_WINDOW = 200
LLM_RELEASE_GATE_THRESHOLD = 0.55
LLM_EVAL_RESULTS_PATH = BASE_DIR / 'eval_results.json'
LLM_HEALTH_ERROR_RATE_DEGRADED = 2.0
LLM_HEALTH_ERROR_RATE_CRITICAL = 10.0
LLM_HEALTH_LATENCY_DEGRADED    = 3000
LLM_HEALTH_LATENCY_CRITICAL    = 10000
LLM_HEALTH_DRIFT_DEGRADED      = 1
LLM_HEALTH_DRIFT_CRITICAL      = 5
ALERTING_COOLDOWN_MINUTES = 10
ROLLBACK_SCRIPT_PATH      = BASE_DIR / 'scripts' / 'rollback.sh'
EMAIL_HOST          = 'smtp.gmail.com'
EMAIL_PORT          = 587
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = 'bouguerrae63@gmail.com' 
EMAIL_HOST_PASSWORD = 'mmkf uovt swnt gtke'            
DEFAULT_FROM_EMAIL  = 'eya.bouguerra@sesame.com.tn'